name: Request to bump

on:
  issue_comment:
    types: [ created ]

jobs:
  bump:
    name: Bump version triggered by PR comment
    if: github.event.issue.pull_request
    uses: bitomic/utilities/.github/workflows/actions-bump.yml@d4b32976beac80f64283f2069c83ca630cc52bc8
    with:
      author_association: ${{ github.event.comment.author_association }}
      comment: ${{ github.event.comment.body }}
      pull_request: true
