name: Request to bump

on:
  issue_comment:
    types: [ created ]

jobs:
  bump:
    uses: bitomic/utilities/.github/workflows/actions-bump.yml@9b265d48125fbba5dd25ea17eef5fbfa0e8862d7
    if: github.event.issue.pull_request
