name: Request to bump

on:
  issue_comment:
    types: [ created ]

jobs:
  bump:
    name: Bump version triggered by PR comment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug
        run: |
          echo ${{ github.event.issue.pull_request }}
          echo ${{ github.event.comment.author_association }}
          echo ${{ github.event.comment.body }}

      - name: Bump
        uses: bitomic/utilities/.github/workflows/actions-bump.yml@0cf1471a1783aba4031e799ade9dc0ad616c137e
        if: github.event.issue.pull_request
        with:
          author_association: ${{ github.event.comment.author_association }}
          comment: ${{ github.event.comment.body }}
          pull_request: true
