name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  build:
    uses: bitomic/utilities/.github/workflows/docker-build.yml@79394997bd793ba79b61f77805184861350f6d46
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
