name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  build:
    uses: bitomic/utilities/.github/workflows/docker-build.yml@f697a9da1a137cbdb6e716a71305813c27b6fbe8
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
